include(GoogleTest)

# Add test targets here.


# StrVec 테스트 예시

# add_executable(
#   StrVec_test
#   StrVec_test.cc
# )
# target_link_libraries(
#   StrVec_test
#   PRIVATE
#   StrVec_lib
#   project_warnings
#   project_sanitizers
#   GTest::gtest_main
# )
# gtest_discover_tests(
#   StrVec_test
# )

